### ISSUE TITLE
[suggestion] Siren

### ISSUE THREAD

**Issue by donjan** [Keyhabit/Focal-keyboard-layout#1]
Hi. Thanks for this great layout, it's quickly shaping up to become my default for the foreseeable future.

While the project is still young and malleable, I wanted to suggest renaming it to **Siren**, on account of the letter placement allowing this word to be written out in a fun way. (and somewhat leaning on the idea behind Sturdy)

From a quick googling, there seems to be more than one keyboard model named Siren on the market, but no layout per se, so I don't think there would be "trademark issues".

**Comment by Keyhabit** [comment]
Hi donjan!

Very glad you are happy with this layout, and also thanks for your creative and validated naming idea. Alas, I don't want to invest time into renaming it at this point. Pascal Getreuer has it listed on his website under its current name and I don't want to have to ask him to change stuff and have to go back myself to the initial Reddit post, change that etc.

**Comment by donjan** [comment]
Fair enough, just didn't want to let this shower thought go undocumented.
Cheers.
